kind: Deployment
apiVersion: apps/v1
metadata:
  name: qbittorrent
  namespace: gluetun-qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      volumes:
        - name: qbit-downloads
          hostPath:
            path: /var/mnt/qbit-test
            type: DirectoryOrCreate
      containers:
        - name: vpn
          image: qmcgaw/gluetun
          env:
            - name: VPN_SERVICE_PROVIDER
              value: private internet access
            - name: VPN_TYPE
              value: openvpn
            - name: OPENVPN_USER
              value: p6379377
            - name: OPENVPN_PASSWORD
              value: password
            - name: SERVER_REGIONS
              value: Netherlands
            - name: VPN_PORT_FORWARDING
              value: 'on'
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: '0'
            - name: PGID
              value: '0'
            - name: WEBUI_PORT
              value: '8080'
          volumeMounts:
            - name: qbit-downloads
              mountPath: /downloads
