kind: Service
apiVersion: v1
metadata:
  name: qbittorrent-service
  namespace: gluetun-qbittorrent
  labels:
    app: qbittorrent 
spec:
  type: ClusterIP  
  ports:
    - name: http-webui 
      protocol: TCP
      port: 8080       
      targetPort: 8080 
  selector:
    app: qbittorrent
